# -*- coding: utf-8 -*-
"""Assigmet-2_Kecerdasan Buatan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e76XJpGtGNqzeEdfQoX4kbnUotPQV-7Z
"""

import numpy as np
import matplotlib.pyplot as plt

def triangle(x, a, b, c, d, e):
    """
    Calculates the membership value for a triangular fuzzy function using if/elif/else.

   Parameter:
    x (float atau np.array): Nilai input yang akan dihitung.
    a (float): Titik X paling kiri, yang berpasangan dengan nilai y (d).
    b (float): Titik X tengah, yang berpasangan dengan nilai Y sebesar 1.
    c (float): Titik X paling kanan, yang berpasangan dengan nilai Y (e).
    d (float): Nilai y pada titik a.
    e (float): Nilai y pada titik c.

    Returns:
    float or np.array: The membership value(s).
    """

    if x < a:
        return d
    elif a <= x <= b:
        return (x - a) / (b - a)
    elif b < x <= c:
        return (c - x) / (c - b)
    elif x > c:
        return e
    else:
        return 0

#Input suhu yang ingin diuji
suhu_air = 32.5

# 1. Suhu Dingin
out_dingin = triangle(suhu_air, 15, 15, 25, 1, 0)

print("Dingin =", out_dingin)

suhu_air_array = np.linspace(10, 40, 1000)   # input (sumbu X)

fuzzified_as_dingin = np.zeros_like(suhu_air_array)   # output (sumbu Y)

# Evaluasi elemen Suhu air dingin untuk grafik
for i, val in enumerate(suhu_air_array):
    fuzzified_as_dingin[i] = triangle(val, 15, 15, 25, 1, 0)

# Menampilkan elemen Suhu ruangan untuk grafik-Dingin
plt.figure(figsize=(10,5))

plt.plot(suhu_air_array, fuzzified_as_dingin, color='red', label='Dingin')

# 1. Tambahkan garis vertikal untuk nilai input
plt.axvline(suhu_air, color='orange', linestyle='--')

# 2. Tampilkan nilai numerik di atas garis (Perbaikan Utama)
# Koordinat X = suhu_air + sedikit offset agar tidak menempel
# Koordinat Y = 0.5 (tengah grafik)
plt.text(suhu_air + 0.5, 0.5, f't = {suhu_air}', color='orange', fontweight='bold')

plt.xlabel('Temperatur t')
plt.ylabel(r'$mu_s(t)$')
plt.title('Fuzzification of Room Temperature')

plt.legend()
plt.grid()

plt.show()

#Input suhu yang ingin diuji
suhu_air = 32.5

# 2. Suhu Sedang
out_sedang = triangle(suhu_air, 15, 25, 35, 0, 0)

print("Sedang =", out_sedang)

suhu_air_array = np.linspace(10, 40, 1000)   # input (sumbu X)

fuzzified_as_sedang = np.zeros_like(suhu_air_array)   # output (sumbu Y)

# Evaluasi satu persatu elemen suhu air
for i, val in enumerate(suhu_air_array):
    fuzzified_as_sedang[i] = triangle(val, 15, 25, 35, 0, 0)

# Menampilkan elemen Suhu ruangan untuk grafik-Sedang
plt.figure(figsize=(10,5))

plt.plot(suhu_air_array, fuzzified_as_sedang, color='green', label='Sedang')

# 1. Tambahkan garis vertikal untuk nilai input
plt.axvline(suhu_air, color='orange', linestyle='--')

# 2. Tampilkan nilai numerik di atas garis (Perbaikan Utama)
# Koordinat X = suhu_air + sedikit offset agar tidak menempel
# Koordinat Y = 0.5 (tengah grafik)
plt.text(suhu_air + 0.5, 0.5, f't = {suhu_air}', color='orange', fontweight='bold')

plt.xlabel('Temperatur t')
plt.ylabel(r'$\mu_s(t)$')
plt.title('Fuzzification of Room Temperature')

plt.legend()
plt.grid()

plt.show()

#Input suhu yang ingin diuji
suhu_air = 32.5


# 3. Suhu Panas
out_panas = triangle(suhu_air, 25, 35, 35, 0, 1)

print("Panas =", out_panas)

suhu_air_array = np.linspace(10, 40, 1000)   # input (sumbu X)

fuzzified_as_panas  = np.zeros_like(suhu_air_array)   # output (sumbu Y)

# Evaluasi satu persatu elemen suhu air
for i, val in enumerate(suhu_air_array):

    fuzzified_as_panas[i]  = triangle(val, 25, 35, 35, 0, 1)

# Menampilkan elemen Suhu ruangan untuk grafik-Panas
import matplotlib.pyplot as plt

plt.figure(figsize=(10,5))

# Plot kurva keanggotaan
plt.plot(suhu_air_array, fuzzified_as_panas, color='blue', label='Panas')

# 1. Tambahkan garis vertikal untuk nilai input
plt.axvline(suhu_air, color='orange', linestyle='--')

# 2. Tampilkan nilai numerik di atas garis (Perbaikan Utama)
# Koordinat X = suhu_air + sedikit offset agar tidak menempel
# Koordinat Y = 0.5 (tengah grafik)
plt.text(suhu_air + 0.5, 0.5, f't = {suhu_air}', color='orange', fontweight='bold')

plt.xlabel('Temperatur t')
plt.ylabel(r'$\mu_s(t)$')
plt.title('Fuzzification of Room Temperature')

plt.legend()
plt.grid()

plt.show()